### PR TITLE
Adds Windows support, docs, Continuous Integration

### LINKED ISSUE #3: libhand-windows
Hi,all

I want to ask if LIBHAND could be compiled and used in windows if using OGRE and BOOST win32 libraries. Do anyone successfully finished it? Thanks.

scvman

### PR DESCRIPTION
**Pull request by shasheene**
Hi Jon,

As mentioned in #1, there are several public forks of libhand on GitHub. [Mega28](https://github.com/Mega28/libhand/commits/master), [Galatasaray University's fork](https://github.com/galatasarayuniversity/libhand) (which is a university in Turkey) and a separate upload of libhand 0.9 by [jsupancic](https://github.com/jsupancic/libhand-public). In pull request #1, I cherry-picked and refactored the commits from some of those forks to enable compilation on modern Debian/Ubuntu systems.

Earlier this year, I constructed a new branch consolidating the rest of the useful commits from those forks, cherry-picking commits of general use from Galatasaray University's fork and Mega28's Windows support to this LibHand branch (closes #3). The commits weren't in a mergeable state (train of thought development branches) so I've adapted them to ensure building on both Linux and Windows works fine.

Additionally, I've put in quite a lot of work to write quality documentation, automating and testing the Windows build -- manual dependency satisfaction and building on Windows was a big pain. With this painful task of build documentation and automation completed, we get a huge payoff: Travis CI and AppVeyor build bot integration. That's something I wish LibHand had for a long time -- hopefully this will stop LibHand's bitrot in future on supported platforms, but will require accounts to be created on both these (highly reputable) services.

If you're happy with the commit series, here is the body of the commit message I request to be used on the merge commit:

> Adds Windows support, docs, Continuous Integration
> 
> Consolidates public GitHub forks, adds build documentation and integrates continuous integration

P.S. When I created the branch, libhand.org went offline for several month duration, but when I check now it has since come back online (no new updates though). This affects some of my changes slightly, but not much. 

P.P.S. LibHand appears to pretty abandoned (public branches adding functionality never attempting to merge upstream, original author not responding to emails), I have maintained backwards compatibility with LibHand 0.9, and have a whole heap of ideas for improvements (both backwards compatible '0.9.z' branch, and more forward looking improvements including dropping OGRE 3D, dropping Tcl/Tk, MacOS support, Android support, more streamlined APIs etc). Lowering the number of dependencies will ease cross-platform compatibility.

I'm very interested in being the formal maintainer of LibHand (currently I'm basically the defacto maintainer). Given Marin Saric doesn't appear to be around, I suggest we can move the libhand repository to github.com/libhand/libhand with both me and you as administrators on the repository -- the ability to re-open (and close) GitHub issues, merge onto master branch, create branches on the repository etc will greatly aid my ability to vastly improve LibHand in public.

### CODE REVIEW

**Comment by jonkeane** [comment]
Transitioning over to github.com/libhand/libhand sounds like a great idea. I've got a bit of time over the next few days. If you want, I will review these commits and test building libhand on the environments I have access to. I'll merge the PR, and then we can work on getting the new dedicated libhand org set up.

**Comment by shasheene** [comment]
Ok sounds great!

I'm of course happy to address any review comments you may have. It's a relatively large Pull Request so take your time. That said, most of it should be relatively braindead (and documentation).

I don't envy those who have to do builds on Windows. The instructions in /docs/build_instructions/windows/BUILD.WINDOWS.md are very thorough and should be easy to follow (when rendered into HTML on GitHub), but for my own sanity I needed to use Chocolatey package manager and created a Bash script to automate the build. It's not ideal -- Bash is not native to Windows and Chocolatey package manager is far from perfect -- but the ease of build is worth it. Unit tests with AppVeyor build bot should take away most of the Windows pain going forward (admittedly in exchange for adding a bit of pain to maintain the AppVeyor/Travis configuration files).

**Comment by jonkeane** [comment]
Ok, I've merged it, this is really great, and a lot of work on your part! The only thing that I found that could be updated is that both Ubuntu 12.04 and 14.04 need to use `libogre-dev` instead of `libogre-1.9-dev` But that's super minor. 

Additionally, I was able to get this compiling on macOS (nee OS X) again. I'm working on making that reproducible, and will get a pull request put together. 

Do you want to create the libhand github org so we can move this over?

**Comment by shasheene** [comment]
Thanks for the kind words!

I actually noticed the libogre-dev vs libogre-1.9-dev thing and made a mention in docs/build_instructions/debian/BUILD.DEBIAN.md (EDIT: Oh, I see what you mean only 12.04 was mentioned there)

macOS support will be great if you can get it. I really wish OGRE 3D itself would package up OGRE 3D and place it on Homebrew and MacPorts. Makes life much easier for developers.

I've created a GitHub organisation at https://github.com/libhand and invited you as the second owner.

> Member
> Members can see all other members, and can be granted access to repositories. They can also create new teams and repositories.
> Owner
> Owners have full administrative rights to the organization and have complete access to all repositories and teams.

If Marin Saric ever returns, I'd be happy to have him as an owner as well, given he's the original author. In principle, I'm happy to have anyone who demonstrates quality Pull Requests, to become a 'member' with permission to [merge and close pull requests](https://help.github.com/articles/repository-permission-levels-for-an-organization/). Hopefully libhand will become a stable and useful library for a lot of people.

Here is the documentation on [transferring repositories to a GitHub organisation](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)

Once transferred, I'll open a PR to update the links to Travis CI/AppVeyor SVG images in the README.md to point to the new GitHub organisation.

**Pull request merged**
