### PR TITLE
Macos build support

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by shasheene** [comment]
Nice work! :smiley: 

I'll thoroughly review PR in a few days!

**Comment by jonkeane** [comment]
I've actually made a few additions, I was able to get (most of) the CI process to work on Travis for the OSX builds, which should help with stability going forward. If you want, I can close this PR and make another with that included. Or I can wait for feedback, and include those changes as well as the new CI configuration. Whichever is easier for you.

**Comment by shasheene** [comment]
No need to close this PR, you can push any changes to this PR by simply pushing (or more likely force pushing with `git push -f`) updates to your forked repository remote and the commits listed in this PR should update automatically.

It looks like you may have already done that, but if you have any new changes feel free to push them as many times as you want, and I'll review the latest set on the weekend!

**Comment by jonkeane** [comment]
Ah yes, of course! Despite the fact that the automatic addition of pushes to a PR has bitten me in the past, I totally forgot that that's what it does. Yeah, it looks like everything is there (and travis is still passing). So feel free to work on it whenever.

**Comment by shasheene** [comment]
Good changes. I’ve now checked out your pull request locally, and reviewed it. I’ve addressed some minor things with no functional impact. On my aging mid-2010 Macbook Pro I booted into an old Yosemite partition (usually use Debian on that machine) after a lot Homebrew prompts and built and ran pose_desiginer. Good stuff!

Here is a description of my minor changes that don't affect functionality:

1. Squash PR into 3 commits
* I used a git [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) to squash the chronological sequence of twenty developmental/train-of-thought commits (containing the fiddly iterative debugging of .travis.yml) to just 3 commits (Updates to source code, updates to docs and adding macOS build to Travis CI).
* This removes superfluous commits, such as the merge commit and commits reverting changes that just occurred earlier in the pull request. The admitted downside to Git interactive rebasing is a loss of chronological development history, and potentially information in previous commit messages (though the most important information from commit message history can of course always be placed as code comments), as well as labor time actually doing the rebase operations and steep git learning curve (easily can get into a position to require hard resetting to commits listed in `git reflog`). The upside is a small and easily reviewable number of commits for public consumption.

2. Random stylistic things: Whitespace, CMake capitalization etc
* Some modified CMakeLists.txt function calls weren’t capitalized. Not my personal preference either but defacto code standard in the pre-existing LibHand codebase. I note that I didn’t remember to keep all caps in every CMakeLists.txt line I’ve modified in prior commits either. I’ve constructed a new patch to modify the existing CMakeLists.txt capitalizations (#9) and amended the lines that you modified here to keep consistency.
* Minor whitespace modification appeared to have been made to random lines (likely automatically by text editor), polluting the git diff (while -w flag can ignore this, it's not ideal)
    * I have no problems with removal of superfluous (eg, trailing) whitespace if any, but that would be as a separate patch, and IMO would need (prior or subsequent, doesn't really matter) agreement of standardization on editor settings to prevent back-and-forth battle between respective editors slightly different automatic formatting settings.
    * I used `git add -p` to select the portions of interest, and ensured the commits retain your authorship.
* Ultra minor modifications to README.md and BUILD.MACOS.md content for consistency.

In the interests of being prohibited from merging my commits without review, you can review and merge my PR that contains some base commits used here, #9.

Please have a quick glance over to this PR, if you’re happy with my modifications to it please say so and after #9 has been merged, I’ll merge this/your PR (well technically the patches from this PR other than the patches being merged in #9, which this PR now builds on).

**Comment by jonkeane** [comment]
Thanks for this feedback. I totally agree about the whitespace and cmake capitalization. I'm fine with  squashing the chronology of the commits. 

I've merged in #9 so this should be good to go.

**Comment by shasheene** [comment]
Oh seeing the history, I should have rebased this patchset on top of the merge commit of #9 first.

Makes no functional difference, but the commit tree would have been cleaner (the way I was imagining it looks in my head.

**Comment by jonkeane** [comment]
That's not even half as bad as my haphazard commits going back and forth with docs and getting travis working!

**Comment by shasheene** [comment]
Nah that was alright -- that's exactly how everyone does it.

Personally I fork the main repo and push changes to it with a GitHub account linked Travis CI to that public fork, and iterating until all builds pass. That way when it comes to opening a PR, it should all work. Either strategy is as legitimate as the other. Iterating on a PR works too.

A public fork everyone ignores (or a private fork) has the benefit of allowing amended commits to be force pushed publicly as no one in their right mind would build on someone's random fork named 'experimental'.

I think I'll be moving away from rebasing as heavily as I do currently after I have an already reasonable patch series. I'm starting to think the benefits aren't worth the time it takes, unless I can find more efficient workflows (especially for private projects). Big projects like [the Linux kernel](https://www.kernel.org/pub/software/scm/git/docs/user-manual.html#patch-series) benefit from it much more

**Pull request merged**
